設計書作成-在庫一覧画面
KaitoDokan/digital-ojt-development-cause-DroneInventorySystem pull request #18
Opened 2024-11-15 01:40 UTC by KaitoDokan

## 概要

在庫一覧画面の設計書変更
・在庫一覧表示
・検索機能
・データ出力機能

のコミットをしていきます、最後のコミットが承認された時点でマージする想定です

## 実装方針・詳細

機能ごとでの設計書変更＆コミット

## 影響範囲

特になし

## テスト

特になし

2024-11-15 06:30 UTC, aoyagi96 approved these changes
- 画面に吹き出しによる補足説明はわかりやすくて良いですね。
- 何をキーにデータを取得するか書かれているのはグッドです！

2024-11-18 13:38 UTC, aoyagi96 reviewed
現時点で気になったところをコメントしました！

2024-11-18 13:38 UTC, aoyagi96 commented on docs/【DIGITAL OJT】WBS.xlsx
今回成果物が詳細設計書、ソースコード、試験項目書兼結果報告書になるかと思いますが、それぞれ成果物がいつ完成するかも記載をお願いします。

2024-11-18 13:38 UTC, aoyagi96 commented on docs/詳細設計書/設計書_在庫一覧画面.xlsx
- 初期表示の説明は具体的に書かれていて良いと思いました！
- 分類名　在庫名　在庫数で複数の条件が指定された場合、ANDで結合でしょうか？ORで結合でしょうか？
- 在庫名は部分一致と完全一致のどちらでしょうか？
- 入力チェックでエラーの場合はどんな感じに表示されますか？

2024-11-19 04:56 UTC, KaitoDokan commented on docs/詳細設計書/設計書_在庫一覧画面.xlsx
・複数条件指定時はORにしてしまうと矛盾が生じる恐れがあるためAND結合にします。
例：category_id 1 name ほげ(カテゴリ1に属していないもの)
のように検索した場合、カテゴリ1のものすべて＋ほげ が表示されてしまうと考えています。

・分類名、在庫名はプルダウンで選択の為必ず完全一致になります。
・入力チェックでのエラー表示画面イメージ追加しておきます！

2024-11-20 03:04 UTC, aoyagi96 requested changes
コメントの確認をお願いします。

2024-11-21 14:11 UTC, aoyagi96 reviewed
ログ設計のところ、細かいですが対応をお願いします。

2024-11-21 14:11 UTC, aoyagi96 commented on docs/詳細設計書/共通設計書_ログ設計.xlsx
内容としてはOKです。
ログの種類等、非常にわかりやすいですね！
フォーマットですが、在庫一覧の詳細機能と同じにしてください。（作成者、更新者等管理できるように）
本来は共通仕様用のフォーマットを用意すべきですが、とりあえず。

2024-11-21 14:15 UTC, aoyagi96 commented on docs/詳細設計書/詳細設計書_在庫一覧画面.xlsx
修正内容を確認しました。
OKです！

2024-11-25 10:05 UTC, aoyagi96 reviewed
確認しました！

2024-11-25 10:05 UTC, aoyagi96 commented on docs/詳細設計書/詳細設計書_在庫センター情報画面.xlsx
修正を確認しました。

2024-11-26 07:30 UTC, aoyagi96 reviewed
コメントをご確認ください。

2024-11-26 07:30 UTC, aoyagi96 commented on docs/詳細設計書/詳細設計書_在庫センター情報画面.xlsx
- 削除詳細処理
  - 在庫一覧で使用されているかどうかはチェックし、使われていたら削除できないようにした方が良いかと思います。

2024-11-27 01:19 UTC, aoyagi96 approved these changes
LGTM
開発中に記載漏れや考慮漏れ等発生した場合は、都度アップデートをお願いします。

2024-11-27 01:19 UTC, aoyagi96 commented on docs/詳細設計書/詳細設計書_在庫センター情報画面.xlsx
確認しました！

2024-11-27 01:30 UTC, merged